version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb 
      POSTGRES_PASSWORD: password
      POSTGRES_USER: myuser 
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
